version: "3.8"

x-app: &app
  build:
    context: .
    dockerfile: Dockerfile
    args:
      RUBY_VERSION: '3.0.2'
      BUNDLER_VERSION: '2.2.31'
      NODE_MAJOR: '16'
  env_file: .env

services:
  webpacker:
    <<: *app
    command: bash -c 'rm -rf public/packs/* || true && bundle exec rake react_on_rails:locale && bin/webpack-dev-server'
    volumes:
      - .:/application:cached
      - rails_cache:/application/tmp/cache
      - bundle:/usr/local/bundle
      - node_modules:/application/node_modules
      - packs:/application/public/packs
    ports:
      - '3035:3035'
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  web:
    <<: *app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/application
      - rails_cache:/application/tmp/cache
      - bundle:/usr/local/bundle
      - node_modules:/application/node_modules
    ports:
      - '3000:3000'
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - DATABASE_URL=postgres://postgres:postgres@database:5432/
    depends_on:
      - database
      - webpacker

  database:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_14_1:/var/lib/postgresql/data
        #healthcheck:
        #  test: pg_isready -U code-challenge-scaffold -h 127.0.0.1
        #  interval: 5s

volumes:
  rails_cache:
  bundle:
  node_modules:
  postgres_14_1:
  packs:
